### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by filypsdias** [filypsdias/StackTrace#1]
- [ ] Find a consistent database to use in our project
- [ ] Create short presentation
- [ ] Do a Brainstorm
- [ ] Define platform and framework
